package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/kluzzebass/graphql-demo/graph/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Post, error) {
	_, ok := r.UserMap.Get(input.UserID)
	if !ok {
		return nil, fmt.Errorf("user not found")
	}

	if input.ID != nil {
		_, ok := r.PostMap.Get(*input.ID)
		if ok {
			return nil, fmt.Errorf("post already exists")
		}
	} else {
		bigliestID := 0
		for id := range r.PostMap.Keys() {
			if id > bigliestID {
				bigliestID = id
			}
		}
		bigliestID++
		input.ID = &bigliestID
	}

	post := &model.Post{
		ID:        *input.ID,
		Title:     input.Title,
		Ingress:   input.Ingress,
		Content:   input.Content,
		UserID:    input.UserID,
		Category:  input.Category,
		CreatedAt: time.Now(),
	}

	r.PostMap.Set(*input.ID, post)
	r.PostCreatedSub.Publish([]*model.Post{post})

	return post, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id int) (bool, error) {
	_, ok := r.PostMap.Get(id)
	if !ok {
		return false, fmt.Errorf("post not found")
	}

	r.PostMap.Delete(id)
	r.PostDeletedSub.Publish([]int{id})

	return true, nil
}

// User is the resolver for the user field.
func (r *postResolver) User(ctx context.Context, obj *model.Post) (*model.User, error) {
	user, ok := r.UserMap.Get(obj.UserID)
	if !ok {
		return nil, fmt.Errorf("user not found")
	}

	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users := []*model.User{}
	for user := range r.UserMap.Values() {
		users = append(users, user)
	}

	return users, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts := []*model.Post{}
	for post := range r.PostMap.Values() {
		posts = append(posts, post)
	}

	return posts, nil
}

// PostCreated is the resolver for the postCreated field.
func (r *subscriptionResolver) PostCreated(ctx context.Context) (<-chan *model.Post, error) {
	log.Println("postCreated subscription started")
	sub := r.PostCreatedSub.Subscribe(ctx, func(msg *model.Post) bool {
		return true
	})

	return sub.Chan(), nil
}

// PostDeleted is the resolver for the postDeleted field.
func (r *subscriptionResolver) PostDeleted(ctx context.Context) (<-chan int, error) {
	log.Println("postDeleted subscription started")
	sub := r.PostDeletedSub.Subscribe(ctx, func(msg int) bool {
		return true
	})

	return sub.Chan(), nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User) ([]*model.Post, error) {
	posts := []*model.Post{}
	for post := range r.PostMap.Values() {
		if post.UserID == obj.ID {
			posts = append(posts, post)
		}
	}

	return posts, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
